name: tmeny_flutter
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # common packages
  intl: ^0.17.0
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  dropdown_button2: ^2.1.0
  graphql_flutter: ^5.1.2
  gql_http_link: ^0.4.0
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.0.20
  devicelocale: ^0.6.0
  get_it: ^7.2.0
  sizer: ^2.0.15
  json_annotation: ^4.8.0
  flutter_svg: ^2.0.4
  iconsax: ^0.0.8
  smooth_page_indicator: ^1.1.0

  # otb form
  pin_code_fields: ^7.4.0

  # firebase
  firebase_core: ^2.4.1
  firebase_messaging: 14.2.1

  # social login
  sign_in_with_apple: ^4.3.0
  flutter_facebook_auth: ^4.3.2
  google_sign_in: ^6.0.2

  # notification
  eraser: ^2.0.1
  flutter_local_notifications: ^13.0.0

  # other packages
  video_player: ^2.6.0     # for walkthrough Bg video
  image_picker: ^0.8.7+3   # to get images from device
  flutter_rating_bar: ^4.0.1
  photo_view: ^0.14.0
  image_cropper: ^3.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.12.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

flutter:

  uses-material-design: true

  assets:
    - fonts/

    - assets/images/
    - assets/native_splash/
    - assets/launcher_icons/
    - assets/walkthrough/
    - assets/bookings/
    - assets/flags/

    - i18n/common/
    - i18n/tour_guide/
    - i18n/user/
    - i18n/user/user_authentication/
    - i18n/user/user_walkthrough/

    - assets/icons/
    - assets/icons/authentication/


  fonts:
    - family: LamaSans
      fonts:
        - asset: fonts/LamaSans-Black.ttf
          weight: 900
        - asset: fonts/LamaSans-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: fonts/LamaSans-Bold.ttf
          weight: 700
        - asset: fonts/LamaSans-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/LamaSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/LamaSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/LamaSans-ExtraLight.ttf
          weight: 200
        - asset: fonts/LamaSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/LamaSans-Light.ttf
          weight: 300
        - asset: fonts/LamaSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/LamaSans-Medium.ttf
          weight: 500
        - asset: fonts/LamaSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/LamaSans-Regular.ttf
          weight: 400
        - asset: fonts/LamaSans-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: fonts/LamaSans-SemiBold.ttf
          weight: 600
        - asset: fonts/LamaSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/LamaSans-Thin.ttf
          weight: 100
        - asset: fonts/LamaSans-ThinItalic.ttf
          weight: 100
          style: italic


